### ISSUE TITLE
Parsing JSON in hubot pack

### ISSUE THREAD

**Issue by jtopjian** [StackStorm/st2incubator#218]
I wanted the output of actions to look cleaner when being executed by hubot in Slack, so I tried printing raw JSON. Surprisingly, I would get no output at all. 

I narrowed the problem down to the `format_localrunner_result` function in `post_result.py`. Because `stdout` was converted to proper JSON, `strip()` was failing. The following change worked for me:

```python
def format_localrunner_result(result, do_serialize=True):
    output = format_possible_failure_result(result)
    # Add in various properties if they have values
    stdout = result.get('stdout', None)
    if stdout:
        try:
            output['stdout'] = stdout.strip()
        except AttributeError:
            output['stdout'] = stdout
    stderr = result.get('stderr', None)
    if stderr:
        output['stderr'] = stderr.strip()
    return_code = result.get('return_code', 0)
    if return_code != 0:
        output['return_code'] = return_code
    error = result.get('error', None)
    if error:
        output['error'] = error

    return _serialize(output) if do_serialize else output
```

It looks like a similar change needs done in `format_pythonrunner_result`.

I would make a proper pull request for this, but I'm not sure if this is the best way or place to handle this change.

**Comment by manasdk** [comment]
Makes sense, only comment is I would write it as 

output['stdout'] = stdout.strip() if isinstance(stdout, six.string_types) else stdout

Feel free to open a PR :).

**Comment by jtopjian** [comment]
@manasdk @jfryman Thanks, guys :smile:

**Comment by jtopjian** [comment]
@manasdk @jfryman actually, it looks like that patch didn't work:

```
output[\'stdout\'] = stdout.strip()\nAttributeError: \'dict\' object has no attribute \'strip\'\n'
```
