### ISSUE TITLE
Update actions and workflows for v0.8

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2incubator#69]
When we upgrade st2master to v0.8, we will need to update a bunch of actions and workflows because of backward incompatible changes in v0.7 and v0.8.

Some things I have noticed:

* action metadata will need to be updated, we will need to remove definitions for the runner parameters
* `core.local` - runner doesn't return hostname in the result anymore (`process_build_number.localhost.stdout` will need to change to `process_build_number.stdout`, etc.).
* replace ref=core.remote cmd=sudo... with ref=core.remote_sudo cmd=... (core.remote_sudo was broken pre v0.7)
* remove `sudo: true` parameter from `core.remote_sudo` actions

**Comment by DoriftoShoes** [comment]
All these changes were made.
